// Copyright (C) 2026 DarkMatter Productions. GPL-3.0-or-later.
#include "Interaction.h"
#include <cstdio>
#include <cstdlib>
#include <limits>
using namespace openq4::ui;
static unsigned checks=0;
#define CHECK(v) do{++checks;if(!(v)){std::fprintf(stderr,"FAIL line %d: %s\n",__LINE__,#v);std::exit(1);}}while(false)
static Control Button(){Control c;c.action="test";for(auto state:{ControlState::Default,ControlState::Hover,ControlState::Focus,ControlState::Pressed,ControlState::Disabled})c.states[state]="paint";return c;}
struct Fixture {DocumentModel model;Interaction input;ScrollReadback read;std::string error;
 Fixture(){model.id="scroll";model.root.id="root";Node viewport;viewport.id="viewport";Node button;button.id="content";button.control=Button();viewport.children.push_back(button);model.root.children.push_back(viewport);Node bar;bar.id="bar";bar.control=Button();bar.control->role=ControlRole::Scrollbar;bar.control->action.clear();bar.control->widget=ScrollSpec{"viewport","track","thumb",true,36,36};model.root.children.push_back(bar);Node modal;modal.id="modal";model.root.children.push_back(modal);
  input.Reset(model);CHECK(MeasureScroll({100,1000,0,200,36},read.geometry));read.available=true;read.geometryToken=1;CHECK(input.SetReadbacks({},error));CHECK(input.SetScrollReadbacks({{"bar",read}},error));input.SetBounds({{"bar",{200,0,36,200,true}},{"content",{0,0,100,30,true}}});CHECK(input.Focus("content"));}
 ScrollCommand Take(){auto commands=input.TakeScrollCommands();CHECK(commands.size()==1);CHECK(input.TakeActions().empty());return commands.front();}
 void Step(MenuInput key){input.Input(key,true);input.Input(key,false);}
};
static void Layout(){Fixture f;CHECK(f.input.State("bar")==ControlState::Default);CHECK(f.input.Widget("bar")->scroll->geometry.range==900);auto before=f.input.Widget("bar")->scroll;
 for(int fault=0;fault<9;++fault){auto bad=f.read;switch(fault){case 0:bad.geometryToken=0;break;case 1:bad.dpRatio=0;break;case 2:bad.lineStep=0;break;case 3:bad.geometry.offset=901;break;case 4:bad.geometry.travel=-1;break;case 5:bad.geometry.usable=false;break;case 6:bad.geometry.thumb=201;break;case 7:bad.geometry.track=std::numeric_limits<double>::infinity();break;case 8:bad.geometry.position=201;break;}CHECK(!f.input.SetScrollReadbacks({{"bar",bad}},f.error));CHECK(f.input.Widget("bar")->scroll->geometryToken==before->geometryToken);}
 auto mutated=f.read;mutated.available=false;CHECK(!f.input.SetScrollReadbacks({{"bar",mutated}},f.error));CHECK(f.input.Widget("bar")->scroll->available);++f.read.geometryToken;CHECK(f.input.SetScrollReadbacks({{"bar",f.read}},f.error));mutated=f.read;--mutated.geometryToken;CHECK(!f.input.SetScrollReadbacks({{"bar",mutated}},f.error));
 CHECK(!f.input.SetReadbacks({{"bar",{0.,false,{}}}},f.error));CHECK(!f.input.SetScrollReadbacks({},f.error));CHECK(!f.input.SetScrollReadbacks({{"other",f.read}},f.error));
 CHECK(MeasureScroll({100,100,0,200,36},f.read.geometry));++f.read.geometryToken;CHECK(f.input.SetScrollReadbacks({{"bar",f.read}},f.error));CHECK(!f.input.Focus("bar"));CHECK(f.input.State("bar")==ControlState::Disabled);CHECK(f.input.ScrollPulse("bar",ScrollStep::End)==false);
 CHECK(MeasureScroll({100,1000,0,20,36},f.read.geometry));++f.read.geometryToken;CHECK(f.input.SetScrollReadbacks({{"bar",f.read}},f.error));CHECK(!f.read.geometry.usable&&f.read.geometry.range==900);CHECK(!f.input.Focus("bar"));
}
static void Semantics(){Fixture f;
 f.input.PointerPart("bar",.9,{},false);f.input.Pointer(true);auto page=f.Take();CHECK(!page.drag&&page.step==ScrollStep::PageForward&&f.input.CanDispatchScrollCommand(page));CHECK(f.input.Focused()=="content");auto bad=page;bad.step=static_cast<ScrollStep>(255);CHECK(!f.input.CanDispatchScrollCommand(bad));bad=page;bad.control="content";CHECK(!f.input.CanDispatchScrollCommand(bad));bad=page;bad.sourceToken=0;CHECK(!f.input.CanDispatchScrollCommand(bad));f.input.Pointer(false);CHECK(f.input.TakeActions().empty());
 CHECK(f.input.Focus("bar"));for(auto pair:{std::pair<MenuInput,ScrollStep>{MenuInput::Up,ScrollStep::LineBackward},{MenuInput::Down,ScrollStep::LineForward},{MenuInput::Home,ScrollStep::Start},{MenuInput::End,ScrollStep::End},{MenuInput::PageUp,ScrollStep::PageBackward},{MenuInput::PageDown,ScrollStep::PageForward}}){f.Step(pair.first);const auto command=f.Take();CHECK(command.step==pair.second&&!command.drag&&f.input.CanDispatchScrollCommand(command));}
 f.Step(MenuInput::Accept);CHECK(f.input.TakeActions().empty()&&f.input.TakeScrollCommands().empty());
 f.Step(MenuInput::Down);auto stale=f.Take();f.input.Cancel();CHECK(!f.input.CanDispatchScrollCommand(stale));
 f.Step(MenuInput::Down);stale=f.Take();++f.read.geometryToken;CHECK(f.input.SetScrollReadbacks({{"bar",f.read}},f.error));CHECK(!f.input.CanDispatchScrollCommand(stale));
 f.Step(MenuInput::Down);stale=f.Take();CHECK(f.input.PushModal("modal"));CHECK(!f.input.CanDispatchScrollCommand(stale)&&f.input.TakeScrollCommands().empty());CHECK(f.input.PopModal());
 f.input.Input(MenuInput::Down,true);f.Take();CHECK(f.input.PushModal("modal")&&f.input.PopModal());f.input.Input(MenuInput::Down,true);CHECK(f.input.TakeScrollCommands().empty());f.input.Input(MenuInput::Down,false);f.Step(MenuInput::Down);f.Take();
}
static void Drag(){Fixture f;const double grab=.25;f.input.PointerPart("bar",f.read.geometry.thumb*grab/f.read.geometry.track,{},true);f.input.Pointer(true);CHECK(f.input.CapturedPointerControl()=="bar"&&f.input.Focused()=="content"&&f.input.TakeScrollCommands().empty());
 f.input.PointerPart("bar",.6,{},false);auto move=f.Take();CHECK(move.drag&&move.grabFraction==grab&&move.pointer==120&&f.input.CanDispatchScrollCommand(move));for(int fault=0;fault<3;++fault){auto bad=move;if(fault==0)bad.pointer=std::numeric_limits<double>::infinity();if(fault==1)bad.grabFraction=-.1;if(fault==2)bad.grabFraction=1.1;CHECK(!f.input.CanDispatchScrollCommand(bad));}
 CHECK(MeasureScroll({100,500,0,100,36},f.read.geometry));++f.read.geometryToken;CHECK(f.input.SetScrollReadbacks({{"bar",f.read}},f.error));CHECK(!f.input.CanDispatchScrollCommand(move));f.input.PointerPart("bar",1.3);move=f.Take();CHECK(move.grabFraction==grab&&move.pointer==130);double offset=0;CHECK(ScrollDragOffset(f.read.geometry,move.pointer,move.grabFraction,offset)&&offset==400);
 f.input.Input(MenuInput::Back,true);CHECK(f.input.CapturedPointerControl().empty()&&!f.input.CanDispatchScrollCommand(move)&&f.input.TakeActions().empty());f.input.Pointer(false);f.input.Input(MenuInput::Back,false);CHECK(f.input.Focused()=="content");
 f.input.PointerPart("bar",.05,{},true);f.input.Pointer(true);CHECK(f.input.CapturedPointerControl()=="bar");f.input.PointerPart("bar",{});CHECK(f.input.CapturedPointerControl().empty());f.input.Pointer(false);CHECK(f.input.TakeActions().empty());
 f.input.PointerPart("bar",.05,{},true);f.input.Pointer(true);CHECK(f.input.SetEnabled("bar",false));CHECK(f.input.CapturedPointerControl().empty());CHECK(f.input.SetEnabled("bar",true));f.input.PointerPart("bar",.05,{},true);f.input.Pointer(true);CHECK(f.input.CapturedPointerControl().empty());f.input.Pointer(false);f.input.Pointer(true);CHECK(f.input.CapturedPointerControl()=="bar");
 const auto saved=f.input.CaptureWidgets();CHECK(saved.version==3&&saved.widgets.at("bar").scrollOffsetDp==0.);CHECK(f.input.RestoreWidgets(saved,f.error));CHECK(f.input.CapturedPointerControl().empty()&&f.input.PendingScrollOffset("bar")==0.);CHECK(!f.input.CanActivate("bar"));CHECK(f.input.AcknowledgeScrollRestore("bar",0));f.input.SetBounds({{"bar",{200,0,36,200,true}},{"content",{0,0,100,30,true}}});CHECK(f.input.CanActivate("bar"));
 auto bad=saved;bad.widgets.at("bar").scrollOffsetDp=-1;CHECK(!f.input.RestoreWidgets(bad,f.error));CHECK(!f.input.PendingScrollOffset("bar"));bad=saved;bad.version=2;CHECK(!f.input.RestoreWidgets(bad,f.error));
}
static void InvalidLayout(){Fixture f;f.input.PointerPart("bar",.02,{},true);f.input.Pointer(true);CHECK(f.input.CapturedPointerControl()=="bar");f.input.InvalidateLayout();CHECK(f.input.CapturedPointerControl().empty()&&!f.input.CanActivate("bar"));f.input.PointerPart("bar",.02,{},true);f.input.Pointer(true);CHECK(f.input.CapturedPointerControl().empty());f.input.SetBounds({{"bar",{200,0,36,200,true}},{"content",{0,0,100,30,true}}});CHECK(f.input.Focused()=="content");f.input.Pointer(false);f.input.PointerPart("bar",.02,{},true);f.input.Pointer(true);CHECK(f.input.CapturedPointerControl()=="bar");f.input.Reset(f.model);CHECK(f.input.CapturedPointerControl().empty()&&f.input.TakeScrollCommands().empty());}
static void Quarantine(){Fixture f;CHECK(f.input.Focus("bar"));for(auto key:{MenuInput::Accept,MenuInput::Back,MenuInput::Down}){f.input.QuarantineInput(key,true);CHECK(f.input.TakeActions().empty()&&f.input.TakeScrollCommands().empty());f.input.Input(key,true);CHECK(f.input.TakeActions().empty()&&f.input.TakeScrollCommands().empty());f.input.Input(key,false);}CHECK(f.input.Focus("bar"));f.Step(MenuInput::Down);f.Take();}
int main(){Layout();Semantics();Drag();InvalidLayout();Quarantine();std::printf("PASS %u checks; pure actual Interaction and ScrollGeometry, no layout/native input.\n",checks);}
