// Copyright (C) 2026 DarkMatter Productions. GPL-3.0-or-later.
#include "src/ui/retained/Runtime.h"
#include "src/ui/retained/State.h"
#include "src/ui/retained/ScrollGeometry.h"
#include <RmlUi/Core.h>
#include <RmlUi/Core/ElementDocument.h>
#include <RmlUi/Core/ElementUtilities.h>
#include <json/json.h>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <limits>
#include <sstream>
using namespace openq4::ui;
static unsigned checks=0;
static void Check(bool value,const char* why){++checks;if(!value){std::fprintf(stderr,"FAIL %s\n",why);std::exit(1);}}
static bool Near(double a,double b,double tolerance=1.01){return std::abs(a-b)<=tolerance;}
static Json::Value Typed(const char* type,Json::Value value,const char* unit=nullptr){Json::Value v;v["type"]=type;v["value"]=std::move(value);if(unit)v["unit"]=unit;return v;}
static Json::Value Box(const char* id,double x,double y,double w,double h){Json::Value n;n["id"]=id;n["type"]="group";n["children"]=Json::Value(Json::arrayValue);auto& p=n["properties"];
 p["position"]=Typed("keyword","absolute");p["display"]=Typed("keyword","block");p["opacity"]=Typed("number",1);p["box-sizing"]=Typed("keyword","border-box");
 p["left"]=Typed("length",x,"dp");p["top"]=Typed("length",y,"dp");p["width"]=Typed("length",w,"dp");p["height"]=Typed("length",h,"dp");return n;}
static void Feedback(Json::Value& doc,Json::Value& node){const auto id=node["id"].asString();for(auto* state:{"default","hover","focus","pressed","disabled"})node["control"]["states"][state]=id+"-feedback";
 Json::Value timeline,track;timeline["id"]=id+"-feedback";timeline["durationMs"]=1;track["node"]=id;track["property"]="opacity";for(unsigned time:{0u,1u}){Json::Value k;k["atMs"]=time;k["value"]=Typed("number",1);track["keys"].append(k);}timeline["tracks"].append(track);doc["timelines"].append(timeline);}
static Json::Value Source(bool horizontal=false,bool transform=false,bool framed=false){Json::Value d;d["format"]="openq4-ui";d["version"]=1;d["id"]="scroll-runtime";d["actions"]["button"]["operation"]="test.button";d["actions"]["button"]["arguments"]=Json::Value(Json::objectValue);
 auto root=Box("root",0,0,640,360),frame=Box("frame",90,60,380,245),viewport=Box("viewport",0,0,280,180),content=Box("content",0,0,horizontal?1000:280,horizontal?180:1000);
 viewport["properties"]["overflow"]=Typed("keyword","auto");
 if(framed){viewport["properties"]["border-width"]=Typed("length",2,"dp");viewport["properties"]["padding-top"]=Typed("length",6,"dp");viewport["properties"]["padding-left"]=Typed("length",5,"dp");}
 for(auto item:{std::pair<const char*,double>{"first",0},{"last",850}}){auto button=Box(item.first,horizontal?item.second:8,horizontal?8:item.second,80,32);button["control"]["role"]="button";button["control"]["action"]="button";button["control"]["label"]="#str_test";Feedback(d,button);content["children"].append(button);}
 viewport["children"].append(content);frame["children"].append(viewport);
 auto bar=Box("bar",horizontal?0:300,horizontal?195:0,horizontal?280:36,horizontal?36:180);auto& c=bar["control"];c["role"]="scrollbar";c["label"]="#str_test";c["viewport"]="viewport";c["orientation"]=horizontal?"horizontal":"vertical";c["lineStep"]=36;c["minimumThumb"]=36;c["parts"]["track"]="track";c["parts"]["thumb"]="thumb";Feedback(d,bar);
 auto track=Box("track",0,0,horizontal?280:36,horizontal?36:180),thumb=Box("thumb",0,0,36,36);
 if(framed){track["properties"]["padding-top"]=Typed("length",3,"dp");track["properties"]["padding-left"]=Typed("length",2,"dp");track["properties"]["border-width"]=Typed("length",1,"dp");thumb["properties"]["margin-top"]=Typed("length",2,"dp");thumb["properties"]["margin-left"]=Typed("length",1,"dp");}
 Json::Value colour(Json::arrayValue);for(double value:{1.,.3,.1,1.})colour.append(value);thumb["properties"]["background-color"]=Typed("color",colour);track["children"].append(thumb);bar["children"].append(track);frame["children"].append(bar);
 auto modal=Box("modal",0,0,100,100);frame["children"].append(modal);
 if(transform){Json::Value t(Json::arrayValue);for(double v:{12.,8.,1.1,.85,13.})t.append(v);frame["properties"]["transform"]=Typed("transform",t,"dp");}
 root["children"].append(frame);d["root"]=root;return d;}
static std::string Encode(const Json::Value& d){Json::StreamWriterBuilder w;w["indentation"]="";w["precision"]=17;return Json::writeString(w,d);}
static Json::Value& Frame(Json::Value& d){return d["root"]["children"][0];}
static Json::Value& Bar(Json::Value& d){return Frame(d)["children"][1];}
struct HostFixture final:Host {unsigned errors=0,draws=0;std::uint64_t frame=0;
 bool ReadFile(const std::string&,std::string&)override{return false;}bool ReadCVar(const std::string&,size_t,StateValue&)override{return false;}
 std::string Translate(const std::string& value)override{return value.starts_with("#str_")?"Localized":value;}
 void Log(bool bad,const std::string& message)override{if(bad){++errors;std::fprintf(stderr,"Runtime: %s\n",message.c_str());}}
 std::uintptr_t LoadMaterial(const std::string&,int& w,int& h)override{w=h=64;return 1;}
 void Draw(const std::vector<Vertex>& v,const std::vector<int>& i,std::uintptr_t)override{++draws;bool finite=i.size()%3==0;for(auto n:i)finite&=n>=0&&size_t(n)<v.size();for(auto p:v)finite&=std::isfinite(p.x)&&std::isfinite(p.y);Check(finite,"actual drawn geometry finite");}
 FontMetrics GetFontMetrics(const std::string&,int s)override{return {s*.8f,s*.2f,s*1.4f,s*.5f};}Glyph GetGlyph(const std::string&,int s,std::uint32_t)override{return {s*.5f,0,-s*.8f,s*.5f,float(s),0,0,1,1,"test-font"};}
 std::uint64_t RenderFrame()const override{return frame;}bool BeginLayer(std::uint32_t,int,int)override{return true;}void CompositeLayer(std::uint32_t,std::uint32_t,float,const Bounds&)override{}void MaskLayer(std::uint32_t,std::uint32_t,const Bounds&)override{}void EndLayer(std::uint32_t)override{}
};
struct View {HostFixture host;Runtime runtime{host};Viewport viewport;double time=1;std::string error,source;bool horizontal;
 View(float ratio=1,bool horizontal=false,bool transform=false,bool framed=false):horizontal(horizontal){viewport.width=1280;viewport.height=720;viewport.displayScale=ratio;source=Encode(Source(horizontal,transform,framed));std::vector<Diagnostic> ds;bool ok=runtime.LoadDocument(source,"scroll.q4ui",ds);for(auto& d:ds)std::fprintf(stderr,"%s %s\n",d.pointer.c_str(),d.message.c_str());Check(ok,"scrollbar source loads");runtime.SetReducedMotion(true,time);Frame();}
 void Frame(){time+=.02;++host.frame;runtime.Frame(viewport,time);Check(!host.errors,"runtime no diagnostics");}
 Rml::Element* Element(const char* id){auto* c=Rml::GetContext(0);Check(c&&c->GetDocument(0),"actual Rml document");auto* e=c->GetDocument(0)->GetElementById(id);Check(e!=nullptr,id);return e;}
 double Offset(){auto* e=Element("viewport");return horizontal?e->GetScrollLeft():e->GetScrollTop();}
 ScrollReadback Read(){auto v=runtime.GetWidgetState("bar");Check(v&&v->scroll,"actual scrollbar readback");return *v->scroll;}
 void Key(MenuInput k){runtime.MenuAction(k,true,time);runtime.MenuAction(k,false,time);}
 Rml::Vector2f Point(double fraction){auto* e=Element("track");Rml::Array<Rml::Vector2f,4> q;Check(Rml::ElementUtilities::GetBorderBoxQuad(q,e),"projected track quad");const auto border=e->GetBox().GetSize(Rml::BoxArea::Border),content=e->GetBox().GetSize(Rml::BoxArea::Content);const auto delta=e->GetAbsoluteOffset(Rml::BoxArea::Content)-e->GetAbsoluteOffset(Rml::BoxArea::Border);
  const float x=float((delta.x+(horizontal?fraction:.5)*content.x)/border.x),y=float((delta.y+(horizontal?.5:fraction)*content.y)/border.y);return q[0]+(q[1]-q[0])*x+(q[3]-q[0])*y;}
 void Move(double fraction){const auto p=Point(fraction);runtime.PointerMove(p.x,p.y,time);}
 void Geometry(){auto r=Read();auto* track=Element("track");auto* thumb=Element("thumb");const auto size=thumb->GetBox().GetSize(Rml::BoxArea::Border);Check(Near(horizontal?size.x:size.y,r.geometry.thumb,.01),"authored thumb represents measured range");const auto start=thumb->GetAbsoluteOffset(Rml::BoxArea::Border)-track->GetAbsoluteOffset(Rml::BoxArea::Content);Check(Near(horizontal?start.x:start.y,r.geometry.position,.01),"thumb position equals actual viewport readback");}
 void NoActions(){Check(runtime.TakeActions().empty(),"scrollbar never emits application actions");}
};
static void Schema(){for(bool horizontal:{false,true}){auto source=Source(horizontal);Document d;std::vector<Diagnostic> ds;const bool ok=d.Load(Encode(source),ds);for(auto& diagnostic:ds)std::fprintf(stderr,"%s %s\n",diagnostic.pointer.c_str(),diagnostic.message.c_str());Check(ok,"canonical scrollbar schema accepts");State state;std::string error;Check(state.Reset(d.Model(),error)&&state.ControlValues().empty(),"scrollbar has no application value readback");
 for(int fault=0;fault<15;++fault){auto bad=source;auto& bar=Bar(bad);auto& c=bar["control"];switch(fault){case 0:c["action"]="button";break;case 1:c["event"]="back";break;case 2:c["value"]=0;break;case 3:c["viewport"]="root";break;case 4:c["viewport"]="first";break;case 5:c["viewport"]="bar";break;case 6:c["parts"]["thumb"]="track";break;case 7:c["lineStep"]=0;break;case 8:c["minimumThumb"]=-1;break;case 9:bar["children"][0]["children"][0]["properties"]["position"]=Typed("keyword","relative");break;
 case 10:{auto& p=bar["children"][0]["children"][0]["properties"];p[horizontal?"min-width":"min-height"]=Typed("length",90,"dp");break;}
 case 11:Frame(bad)["children"][0]["modal"]["initialFocus"]="first";break;
 case 12:Frame(bad)["children"][0]["properties"]["overflow"]=Typed("keyword","visible");break;
 case 13:{Json::Value binding;binding["id"]="collision";binding["node"]="thumb";binding["property"]=horizontal?"width":"height";binding["value"]=15;bad["bindings"].append(binding);break;}
 case 14:{auto duplicate=bar;duplicate["id"]="duplicate";duplicate["control"]["parts"]["track"]="duplicate-track";duplicate["control"]["parts"]["thumb"]="duplicate-thumb";duplicate["children"][0]["id"]="duplicate-track";duplicate["children"][0]["children"][0]["id"]="duplicate-thumb";Feedback(bad,duplicate);Frame(bad)["children"].append(duplicate);break;}}
 Check(!d.Load(Encode(bad),ds),"invalid scrollbar schema rejected");}}
}
static void Gestures(){for(float ratio:{1.f,1.25f,2.f})for(bool horizontal:{false,true})for(bool framed:{false,true}){
 View v(ratio,horizontal,true,framed);v.Geometry();Check(v.runtime.FocusControl("first",v.time),"content can focus");const auto initial=v.Offset();auto g=v.Read().geometry;
 v.Move(.9);v.runtime.PointerButton(true,v.time);v.runtime.PointerButton(false,v.time);v.Frame();Check(v.runtime.FocusedControl()=="first","track paging preserves content focus");double expected=0;Check(ScrollStepOffset(g,ScrollStep::PageForward,36*ratio,expected)&&Near(v.Offset(),expected),"track pages by actual viewport with overlap");Check(v.Offset()>initial,"track page moves viewport");v.Geometry();v.NoActions();
 const auto beforeWheel=v.Offset();v.Move(.9);v.runtime.PointerWheel(1,v.time);v.Frame();Check(Near(v.Offset(),beforeWheel+36*ratio),"authored wheel line step");Check(v.runtime.FocusedControl()=="first","wheel preserves content focus");v.NoActions();
 Check(v.runtime.FocusControl("bar",v.time),"explicit navigation focuses scrollbar");v.Key(MenuInput::Home);v.Frame();Check(v.Offset()==0,"Home reaches actual start");v.Key(horizontal?MenuInput::Right:MenuInput::Down);v.Frame();Check(Near(v.Offset(),36*ratio),"axis key line step");v.Key(MenuInput::End);v.Frame();Check(Near(v.Offset(),v.Read().geometry.range),"End reaches exact real range");v.Key(MenuInput::Home);v.Frame();
 g=v.Read().geometry;const double grab=.2;v.Move((g.position+g.thumb*grab)/g.track);v.runtime.PointerButton(true,v.time);v.Frame();Check(v.Offset()==0,"thumb press does not jump to center");
 v.Move(.6);v.Frame();g=v.Read().geometry;Check(ScrollDragOffset(g,g.track*.6,grab,expected)&&Near(v.Offset(),expected),"drag preserves original thumb grab fraction");v.Geometry();
 // Current measured resize changes travel and thumb while the same grab survives.
 auto* track=v.Element("track");Check(track->SetProperty(horizontal?"width":"height",horizontal?"220dp":"140dp"),"resize track");Check(v.Element("content")->SetProperty(horizontal?"width":"height","1500dp"),"resize content while captured");v.Frame();v.Move(.72);v.Frame();g=v.Read().geometry;Check(ScrollDragOffset(g,g.track*.72,grab,expected)&&Near(v.Offset(),expected),"captured resize uses current geometry and original grab");
 v.Move(1.4);v.runtime.PointerButton(false,v.time);v.Frame();Check(Near(v.Offset(),v.Read().geometry.range),"outside release retains final clamped drag");v.NoActions();
 v.Key(MenuInput::Home);v.Frame();g=v.Read().geometry;v.Move(g.thumb*.5/g.track);v.runtime.PointerButton(true,v.time);v.Move(.5);v.Key(MenuInput::Back);const auto canceled=v.Offset();v.Move(.8);v.runtime.PointerButton(false,v.time);v.Frame();Check(v.Offset()==canceled,"Back cancels capture without later release motion");v.NoActions();
 }}
static void DensityKeepsContentFocus(){View v;Check(v.runtime.FocusControl("first",v.time),"focus content before wheel scroll");for(unsigned i=0;i<12;++i){v.Move(.9);v.runtime.PointerWheel(1,v.time);}v.Frame();const double offset=v.Offset();Check(offset>300&&v.runtime.FocusedControl()=="first","wheel leaves earlier focus and scrolls independently");v.viewport.displayScale=2;v.Frame();Check(Near(v.Offset(),offset*2)&&v.runtime.FocusedControl()=="first","density must not reveal unchanged earlier focus");v.viewport.width=1100;v.viewport.height=680;v.Frame();Check(Near(v.Offset(),offset*2),"resize clamps/reflows without revealing unchanged focus");Check(v.runtime.FocusControl("first",v.time),"explicit same focus request");v.Frame();Check(v.Offset()==0,"explicit new focus request reveals earlier content");}
static void MixedViewportReveal(){for(int relation=0;relation<4;++relation)for(float ratio:{1.25f,2.f}){
 View v;auto source=Source();const char* target="mixed-target";const char* legacy="legacy";
 auto button=Box(target,350,400,70,32);button["control"]["role"]="button";button["control"]["action"]="button";button["control"]["label"]="#str_test";if(relation<2)Feedback(source,button);
 auto pane=Box(legacy,relation==0?400:5,relation==0?0:400,200,120),content=Box("legacy-content",0,0,900,900);pane["properties"]["overflow"]=Typed("keyword","auto");content["children"].append(button);pane["children"].append(content);
 if(relation==0)source["root"]["children"].append(pane);
 else if(relation==1)Frame(source)["children"][0]["children"][0]["children"].append(pane);
 else if(relation==2){auto frame=Frame(source);frame["properties"]["left"]=Typed("length",350,"dp");frame["properties"]["top"]=Typed("length",350,"dp");
  pane=Box(legacy,10,10,400,250);pane["properties"]["overflow"]=Typed("keyword","auto");pane["children"].append(frame);source["root"]["children"][0]=pane;target="last";
 }else{Frame(source)["children"][0]["children"][0]["properties"]["width"]=Typed("length",1000,"dp");Frame(source)["children"][0]["children"][0]["children"][1]["properties"]["left"]=Typed("length",850,"dp");target="last";legacy="viewport";}
 v.source=Encode(source);v.runtime.CloseDocument();std::vector<Diagnostic> ds;Check(v.runtime.LoadDocument(v.source,"mixed-scroll.q4ui",ds),"mixed authored and legacy scrollers load");v.Frame();Check(v.runtime.FocusControl(target,v.time),"mixed control focus");v.Frame();auto* owned=v.Element("viewport");auto* old=v.Element(legacy);
 owned->SetScrollTop(300);old->SetScrollLeft(0);if(relation!=3)old->SetScrollTop(0);v.Frame();Check(v.Offset()==300,"ordinary frame leaves authored and legacy manual offsets");
 v.viewport.displayScale=ratio;v.Frame();Check(Near(v.Offset(),300*ratio),"density preserves only authored vertical offset");Check(old->GetScrollLeft()>0&&(relation==3||old->GetScrollTop()>0),"mixed legacy ancestors and perpendicular axis still reveal after density");Check(v.runtime.FocusedControl()==target,"mixed resize preserves focus identity");
 std::string snapshot;Check(v.runtime.SaveSnapshot(snapshot,v.error,v.time),"save mixed focused layout");v.runtime.CloseDocument();Check(v.runtime.LoadDocument(v.source,"mixed-scroll.q4ui",ds)&&v.runtime.RestoreSnapshot(snapshot,v.error,v.time),"restore mixed layout into fresh document");v.Frame();owned=v.Element("viewport");old=v.Element(legacy);Check(Near(v.Offset(),300*ratio),"first restored layout preserves authored vertical offset");Check(old->GetScrollLeft()>0&&(relation==3||old->GetScrollTop()>0),"first restored layout reveals legacy axes alongside authored snapshot");Check(v.runtime.FocusedControl()==target,"mixed first layout retains saved content focus");v.NoActions();
}}
static void Persistence(){View v;Check(v.runtime.FocusControl("bar",v.time),"bar focus");v.Key(MenuInput::PageDown);v.Frame();const auto logical=v.Offset();std::string snapshot;Check(v.runtime.SaveSnapshot(snapshot,v.error,v.time),"save actual scroll snapshot");Json::Value saved;Json::CharReaderBuilder reader;std::istringstream input(snapshot);Check(Json::parseFromStream(reader,input,&saved,&v.error),"decode saved snapshot");Check(saved["widgets"]["version"]==3&&saved["widgets"]["controls"]["bar"]["scrollOffsetDp"].asDouble()==logical,"versioned logical offset persisted");
 v.viewport.displayScale=2;v.Frame();Check(Near(v.Offset(),logical*2),"live density preserves logical scroll offset");v.Frame();Check(Near(v.Offset(),logical*2),"ordinary frame does not replay a density correction");std::string scaledSnapshot;Check(v.runtime.SaveSnapshot(scaledSnapshot,v.error,v.time),"save at changed density");Json::Value scaled;std::istringstream scaledInput(scaledSnapshot);Check(Json::parseFromStream(reader,scaledInput,&scaled,&v.error)&&Near(scaled["widgets"]["controls"]["bar"]["scrollOffsetDp"].asDouble(),logical,.01),"snapshot serializes dp rather than physical pixels");v.Key(MenuInput::End);v.Frame();Check(v.runtime.RestoreSnapshot(snapshot,v.error,v.time),"restore exact source scroll snapshot");v.runtime.ReleaseInputSources();v.Frame();Check(Near(v.Offset(),logical*2),"restored dp offset waits for fresh layout and density");Check(v.runtime.FocusedControl()=="bar","restored scrollbar focus waits for offset and bounds together");v.Geometry();
 auto invalid=saved;invalid["widgets"]["controls"]["bar"]["scrollOffsetDp"]=-1;const auto prior=v.Offset();Check(!v.runtime.RestoreSnapshot(Encode(invalid),v.error,v.time)&&v.Offset()==prior,"invalid snapshot preserves viewport");
 Check(v.Element("content")->SetProperty("height","100dp"),"shrink content container");v.Frame();Check(v.Read().geometry.range>0,"outlying authored child still contributes actual overflow");Check(v.Element("last")->SetProperty("display","none"),"hide outlying child so actual content fits");v.Frame();Check(v.Offset()==0&&!v.Read().geometry.usable&&v.runtime.GetControlState("bar")==ControlState::Disabled,"fitting content has inert authored gutter");
 // Same source replacement retains only offsets from a supported snapshot.
 v.runtime.CloseDocument();std::vector<Diagnostic> ds;Check(v.runtime.LoadDocument(v.source,"scroll.q4ui",ds),"replace document");Check(v.runtime.RestoreSnapshot(snapshot,v.error,v.time),"restore into fresh same-source document");v.Frame();Check(Near(v.Offset(),logical*2),"replacement restores current-density offset");Check(v.runtime.FocusedControl()=="bar","replacement retains restored scrollbar focus after first measured layout");
 Check(v.Element("viewport")->SetProperty("display","none"),"hide viewport");v.Frame();Check(!v.Read().available&&v.runtime.GetControlState("bar")==ControlState::Disabled,"hidden viewport leaves scrollbar inert");Check(v.Element("bar")->GetBox().GetSize(Rml::BoxArea::Border).x>0,"hidden viewport preserves gutter width");
}
static void Lifecycle(){View v;v.Move(.03);v.runtime.PointerButton(true,v.time);v.Move(.5);const auto old=v.Offset();Check(old>0,"captured pointer moves before modal");Check(v.runtime.PushModal("modal",v.time),"modal opens over bar");v.Move(.9);v.runtime.PointerWheel(1,v.time);v.runtime.PointerButton(false,v.time);v.Frame();Check(v.Offset()==old,"modal prevents drag/wheel and release replay");Check(v.runtime.PopModal(v.time),"modal closes");v.Frame();v.NoActions();
 Check(v.runtime.FocusControl("bar",v.time),"focus recovered bar");v.Key(MenuInput::Home);v.Frame();v.Move(.03);v.runtime.PointerButton(true,v.time);Check(v.Element("track")->SetProperty("height","20dp"),"track becomes zero travel during drag");v.Frame();v.Move(.9);v.runtime.PointerButton(false,v.time);v.Frame();Check(v.Offset()==0&&!v.Read().geometry.usable,"zero travel retires drag");Check(v.Element("track")->SetProperty("height","180dp"),"restore track extent");v.Frame();v.Move(.8);v.runtime.PointerButton(false,v.time);Check(v.Offset()==0,"restored track cannot replay unmatched release");
 v.viewport.width=0;v.Frame();Bounds untouched{1,2,3,4};Check(!v.runtime.GetBounds("bar",untouched)&&untouched.x==1&&untouched.width==3,"zero viewport geometry query preserves output");Check(!v.Read().available&&!v.runtime.CanActivateControl("bar",v.time),"zero viewport copied diagnostic is unavailable");v.runtime.MenuAction(MenuInput::Back,true,v.time);v.runtime.MenuAction(MenuInput::Down,true,v.time);v.NoActions();v.Move(.5);v.runtime.PointerButton(true,v.time);v.runtime.PointerButton(false,v.time);v.viewport.width=1280;v.Frame();Check(v.Offset()==0,"zero viewport cannot carry a new pointer gesture");Check(v.runtime.FocusControl("bar",v.time),"bar can explicitly focus after valid recovery");v.runtime.MenuAction(MenuInput::Down,true,v.time);v.runtime.MenuAction(MenuInput::Back,true,v.time);v.Frame();Check(v.Offset()==0,"held navigation cannot revive after zero viewport");v.NoActions();v.runtime.MenuAction(MenuInput::Down,false,v.time);v.runtime.MenuAction(MenuInput::Back,false,v.time);v.Key(MenuInput::Down);v.Frame();Check(v.Offset()==36,"fresh source after release navigates normally");v.NoActions();
}
static void TwoAxes(){View v;auto source=Source();auto horizontal=Source(true);auto bar=Bar(horizontal);bar["id"]="a-horizontal";bar["control"]["parts"]["track"]="horizontal-track";bar["control"]["parts"]["thumb"]="horizontal-thumb";bar["children"][0]["id"]="horizontal-track";bar["children"][0]["children"][0]["id"]="horizontal-thumb";Feedback(source,bar);Frame(source)["children"].append(bar);Frame(source)["children"][0]["children"][0]["properties"]["width"]=Typed("length",1000,"dp");
 v.runtime.CloseDocument();std::vector<Diagnostic> ds;Check(v.runtime.LoadDocument(Encode(source),"dual.q4ui",ds),"same viewport permits unique orthogonal owners");v.Frame();Check(v.runtime.FocusControl("first",v.time),"dual axis content focus");auto* viewport=v.Element("viewport");auto wheel=[&](Rml::Element* element){auto point=element->GetAbsoluteOffset(Rml::BoxArea::Content)+element->GetBox().GetSize(Rml::BoxArea::Content)*.7f;v.runtime.PointerMove(point.x,point.y,v.time);v.runtime.PointerWheel(1,v.time);v.Frame();};
 wheel(viewport);Check(viewport->GetScrollTop()==36&&viewport->GetScrollLeft()==0,"content wheel prefers vertical despite horizontal ID sort order");Check(v.runtime.FocusedControl()=="first","dual content wheel preserves field focus");
 wheel(v.Element("horizontal-track"));Check(viewport->GetScrollTop()==36&&viewport->GetScrollLeft()==36,"direct horizontal artwork selects horizontal axis");wheel(v.Element("track"));Check(viewport->GetScrollTop()==72&&viewport->GetScrollLeft()==36,"direct vertical artwork selects vertical axis");
 Check(v.Element("content")->SetProperty("height","100dp")&&v.Element("last")->SetProperty("display","none"),"vertical content becomes fitting");v.Frame();Check(!v.Read().geometry.usable&&v.runtime.GetWidgetState("a-horizontal")->scroll->geometry.usable,"only horizontal range remains usable");wheel(viewport);Check(viewport->GetScrollTop()==0&&viewport->GetScrollLeft()==72,"content wheel falls back to horizontal when vertical fitting");v.NoActions();
}
static void ThumbFrames(){for(float ratio:{1.f,1.25f,2.f})for(bool contentBox:{false,true}){View v(ratio,false,true,true);auto source=Source(false,true,true);auto& props=Bar(source)["children"][0]["children"][0]["properties"];props["box-sizing"]=Typed("keyword",contentBox?"content-box":"border-box");props["border-width"]=Typed("length",20,"dp");props["padding-top"]=Typed("length",10,"dp");props["padding-bottom"]=Typed("length",10,"dp");v.runtime.CloseDocument();std::vector<Diagnostic> ds;Check(v.runtime.LoadDocument(Encode(source),"thumb-frames.q4ui",ds),"authored thumb border and padding source accepts");v.Frame();auto read=v.Read();Check(read.available&&Near(read.geometry.thumb,60*ratio,.01),"actual thumb frame is minimum measured border extent");v.Geometry();Check(v.runtime.FocusControl("bar",v.time),"framed thumb bar focus");v.Key(MenuInput::End);v.Frame();v.Geometry();Check(Near(v.Read().geometry.position+v.Read().geometry.thumb,v.Read().geometry.track,.01),"framed thumb ends at real track edge");v.Key(MenuInput::Home);v.Frame();auto g=v.Read().geometry;v.Move(g.thumb*.2/g.track);v.runtime.PointerButton(true,v.time);v.Move(.6);v.Frame();double expected=0;g=v.Read().geometry;Check(ScrollDragOffset(g,g.track*.6,.2,expected)&&Near(v.Offset(),expected),"thumb-frame drag uses actual measured extent");
 auto* thumb=v.Element("thumb");Check(thumb->SetProperty("border-width","100dp"),"thumb frame exceeds real track");v.Frame();Check(!v.Read().available&&!v.runtime.CanActivateControl("bar",v.time),"oversized thumb frame is inert");const auto offset=v.Offset();v.Move(.9);v.runtime.PointerButton(false,v.time);v.Frame();Check(v.Offset()==offset,"oversized frame cancels drag before next movement");Check(thumb->SetProperty("border-width","20dp"),"thumb frame fits again");v.Frame();Check(v.Read().available,"fitting thumb frame recovers");v.Geometry();v.NoActions();}}
static void SystemCandidate(const std::string& text){Document document;std::vector<Diagnostic> ds;Check(document.Load(text,ds),"actual SYSTEM candidate parses");State state;std::string error;Check(state.Reset(document.Model(),error),"SYSTEM candidate typed state resets");
 for(float density:{1.f,1.25f,2.f}){HostFixture host;Runtime runtime(host);Check(runtime.LoadDocument(text,"system-candidate.q4ui",ds),"actual SYSTEM candidate Runtime loads");double time=1;Viewport vp;vp.width=1280;vp.height=720;vp.displayScale=density;runtime.SetReducedMotion(true,time);Check(runtime.SetState({{"settings.open",true},{"settings.phase",1.},{"settings.busy",false},{"settings.confirmationVisible",false}},error,time),"SYSTEM active Editing projection");
 auto frame=[&]{time+=.02;++host.frame;runtime.Frame(vp,time);Check(host.errors==0,"SYSTEM no runtime diagnostics");};frame();auto* doc=Rml::GetContext(0)->GetDocument(0);auto* body=doc->GetElementById("settings-body");auto* track=doc->GetElementById("settings_body_scrollbar-track");auto* thumb=doc->GetElementById("settings_body_scrollbar-thumb");Check(body&&track&&thumb,"real authored SYSTEM parts");
 auto read=runtime.GetWidgetState("settings_body_scrollbar")->scroll;Check(read&&read->available&&read->geometry.usable,"SYSTEM actual body has scrolling readback");Check(Near(thumb->GetBox().GetSize(Rml::BoxArea::Border).y,read->geometry.thumb,.01),"SYSTEM vector thumb derives from body extent");Check(thumb->GetTagName()=="q4-node"||thumb->GetTagName()=="q4-vector","SYSTEM authored thumb retained");
 Check(runtime.FocusControl("settings_brightness",time),"SYSTEM content focus");const auto point=track->GetAbsoluteOffset(Rml::BoxArea::Content)+track->GetBox().GetSize(Rml::BoxArea::Content)*.9f;runtime.PointerMove(point.x,point.y,time);runtime.PointerWheel(1,time);frame();Check(body->GetScrollTop()>0&&runtime.FocusedControl()=="settings_brightness","SYSTEM wheel preserves actual field focus");const double logical=body->GetScrollTop()/density;
 vp.displayScale=density==2?1.f:2.f;frame();Check(Near(body->GetScrollTop(),std::min(logical*vp.DpRatio(),double(body->GetScrollHeight()-body->GetClientHeight()))),"SYSTEM live density preserves scroll or clamps smaller reflow range");Check(runtime.FocusControl("settings_body_scrollbar",time),"SYSTEM bar explicit focus");runtime.MenuAction(MenuInput::End,true,time);runtime.MenuAction(MenuInput::End,false,time);frame();Check(Near(body->GetScrollTop(),body->GetScrollHeight()-body->GetClientHeight()),"SYSTEM End reaches true final row");Check(runtime.TakeActions().empty(),"SYSTEM scrollbar no settings operation");Check(host.draws>0,"SYSTEM actual CPU geometry submitted");
 }}
int main(int argc,char** argv){Schema();Gestures();DensityKeepsContentFocus();MixedViewportReveal();Persistence();Lifecycle();TwoAxes();ThumbFrames();if(argc>1){std::ifstream file(argv[1],std::ios::binary);std::string text{std::istreambuf_iterator<char>(file),{}};SystemCandidate(text);}
 std::printf("PASS %u checks; actual canonical schema/Interaction/Runtime/Rml layout; counted host, no native input or GPU qualification.\n",checks);}
