// Copyright (C) 2026 DarkMatter Productions. GPL-3.0-or-later.
// Actual SYSTEM/Runtime/RmlUi and shared profile/transaction source. Counted host;
// not production adapter dispatch, CVar writes, real font shaping or native input.
#include "src/ui/retained/Runtime.h"
#include "src/ui/application/SettingsTransaction.h"
#include "src/framework/PerformancePreset.h"
#include <RmlUi/Core.h>
#include <RmlUi/Core/ElementDocument.h>
#include <RmlUi/Core/ElementText.h>
#include <json/json.h>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <set>
#include <sstream>
using namespace openq4;using namespace openq4::ui;
static unsigned checks=0;
static void Check(bool ok,const char* why){++checks;if(!ok){std::fprintf(stderr,"FAIL %s\n",why);std::exit(1);}}
static std::string Read(const std::string& p){std::ifstream f(p,std::ios::binary);Check(bool(f),"bound source readable");return {std::istreambuf_iterator<char>(f),{}};}
struct TestHost final:Host,SettingsHost {
 StateValues live;std::map<std::string,std::string> strings;unsigned writes=0,observations=0,errors=0,draws=0;std::uint64_t frame=0;float expansion=1;
 bool ReadFile(const std::string&,std::string&)override{return false;}bool ReadCVar(const std::string&,size_t,StateValue&)override{return false;}
 std::string Translate(const std::string& id)override{return strings.contains(id)?strings.at(id):id.starts_with("#str_")?"Localized label":id;}
 void Log(bool bad,const std::string& s)override{if(bad){++errors;std::fprintf(stderr,"Runtime: %s\n",s.c_str());}}
 std::uintptr_t LoadMaterial(const std::string&,int& w,int& h)override{w=h=256;return 1;}
 void Draw(const std::vector<Vertex>& v,const std::vector<int>& i,std::uintptr_t)override{++draws;bool ok=i.size()%3==0;for(auto n:i)ok=ok&&n>=0&&size_t(n)<v.size();for(auto p:v)ok=ok&&std::isfinite(p.x)&&std::isfinite(p.y);Check(ok,"finite indexed actual draw");}
 std::uint64_t RenderFrame()const override{return frame;}bool BeginLayer(std::uint32_t,int,int)override{return true;}void CompositeLayer(std::uint32_t,std::uint32_t,float,const Bounds&)override{}void MaskLayer(std::uint32_t,std::uint32_t,const Bounds&)override{}void EndLayer(std::uint32_t)override{}
 FontMetrics GetFontMetrics(const std::string&,int s)override{return {s*.78f,s*.22f,s*1.4f,s*.5f};}Glyph GetGlyph(const std::string&,int s,std::uint32_t cp)override{float a=s*(cp==' '?.28f:.51f)*expansion+.125f;return {a,0,-s*.78f,a*.9f,float(s),0,0,1,1,"test-font"};}
 bool Read(StateValues& v,std::string&)override{v=live;return true;}bool Defaults(StateValues& v,std::string&)override{v=live;return true;}
 bool Validate(const StateValues& b,const StateValues& c,std::string&)override{if(b.size()!=c.size())return false;for(auto& [k,v]:c)if(!b.contains(k)||b.at(k).index()!=v.index()||!ValidStateValue(v))return false;return true;}
 bool Write(const StateValues&,std::string&)override{++writes;return false;}bool NeedsConfirmation(const StateValues&,const StateValues&)const override{return true;}
 void Locale(const std::string& path){std::istringstream f(::Read(path));std::string line;while(std::getline(f,line)){std::istringstream s(line);std::string k,v;s>>std::quoted(k)>>std::quoted(v);if(k.starts_with("#str_"))strings[k]=v;}for(auto* k:{"#str_229976","#str_229977","#str_229978","#str_229985"})Check(strings.contains(k),"all actual locale preset/status strings exist");}
};
struct View {
 TestHost host;SettingsTransaction tx{host};Runtime runtime{host};Viewport viewport;std::string source,error,message="#str_229982";double time=1;bool pending=false,canApply=false;static constexpr std::uint64_t Owner=29;
 View(const std::string& s,const std::string& locale,float density=1,int width=1280,int height=720,float expansion=1):source(s){
  host.Locale(locale);host.expansion=expansion;Json::Value doc;Json::CharReaderBuilder b;auto reader=std::unique_ptr<Json::CharReader>(b.newCharReader());Check(reader->parse(s.data()+s.find('{'),s.data()+s.size(),&doc,&error),error.c_str());
  for(auto& k:doc["state"].getMemberNames())if(k.starts_with("settings.draft.")){auto d=doc["state"][k];StateValue v;auto type=d["type"].asString();if(type=="number")v=d["initial"].asDouble();else if(type=="boolean")v=d["initial"].asBool();else v=d["initial"].asString();host.live.emplace(k.substr(15),v);}
  Check(host.live.size()==53,"full authored 53-key typed catalog");host.live["com_performancePreset"]=std::string("balanced");host.live["r_brightness"]=1.375;host.live["r_forceAmbient"]=.1375;Check(tx.Begin(Owner).code==SettingsCode::Ok,"begin real transaction");
  std::vector<Diagnostic> ds;bool loaded=runtime.LoadDocument(s,"guis/menu/settings/system.q4ui",ds);for(auto& d:ds)std::fprintf(stderr,"%s: %s\n",d.pointer.c_str(),d.message.c_str());Check(loaded,"actual SYSTEM compiles and loads");viewport.width=width;viewport.height=height;viewport.displayScale=density;runtime.SetReducedMotion(true,time);Sync();Frame();
 }
 void Sync(){StateValues v{{"settings.open",true},{"settings.phase",1.0},{"settings.busy",false},{"settings.confirmationVisible",false},{"settings.dirty",tx.Dirty()},{"settings.canApply",canApply},{"settings.message",message},{"ui.numberDraftsPending",pending},{"ui.numberDraftMessage",std::string("#str_230006")}};for(auto& [k,x]:tx.Draft())v["settings.draft."+k]=x;for(auto& [k,x]:tx.Baseline())v["settings.baseline."+k]=x;Check(runtime.SetState(v,error,time),error.c_str());}
 void Frame(){time+=.02;++host.frame;runtime.Frame(viewport,time);Check(!host.errors,"no runtime diagnostics");}void Key(MenuInput k){runtime.MenuAction(k,true,time);runtime.MenuAction(k,false,time);}
 WidgetViewState Widget(){auto w=runtime.GetWidgetState("settings_preset");Check(w.has_value(),"preset widget exists");return *w;}std::string Alias(const char* id){std::string s;Check(runtime.GetPresentationAlias(id,s),id);return s;}
 Rml::Element* Element(const char* id){auto* c=Rml::GetContext(0);Check(c!=nullptr,"actual Rml context");auto* e=c->GetDocument(0)->GetElementById(id);Check(e!=nullptr,id);return e;}Bounds Box(const char* id){Bounds b;Check(runtime.GetBounds(id,b),id);return b;}
 void Open(){Check(runtime.FocusControl("settings_preset",time),"preset can focus");Key(MenuInput::Accept);Frame();Check(Widget().popupOpen,"choice opens");Check(runtime.TakeActions().empty(),"open emits no action");}
 ControlAction Select(unsigned i){Open();Key(MenuInput::Home);for(unsigned n=0;n<i;++n)Key(MenuInput::Down);Frame();Check(Widget().highlight=="settings_preset-option-"+std::to_string(i),"exact highlight");Check(runtime.TakeActions().empty(),"highlight cannot mutate settings");Key(MenuInput::Accept);auto a=runtime.TakeActions();Check(a.size()==1&&a[0].proposal&&a[0].proposalToken,"one immutable typed proposal");return a.front();}
 StateValues Patch(const PerformancePreset& p){PerformancePresetAssignments a;Check(ExpandPerformancePreset(p,a,error),"shared production expansion");StateValues out;for(auto& x:a){StateValue v;if(auto s=std::get_if<std::string>(&x.value))v=*s;else if(std::holds_alternative<bool>(host.live.at(x.key)))v=std::get<int>(x.value)!=0;else v=double(std::get<int>(x.value));out.emplace(x.key,v);}Check(out.size()==32,"exact32 footprint");return out;}
 SettingsResult Dispatch(const ActionInvocation& a,bool observe=true){NumberDraftSummary d;Check(runtime.QueryNumberDrafts(d,error,time),"actual Number barrier queried");if(!d.blocking.empty())return {SettingsCode::Busy,"local draft"};return tx.EditGenerated(Owner,[&](StateValues& out,std::string& e){const PerformancePreset* p=nullptr;if(a.operation=="settings.system.preset"){Check(a.arguments.size()==1&&std::holds_alternative<std::string>(a.arguments.at("name")),"exact preset operation schema");p=FindPerformancePreset(std::get<std::string>(a.arguments.at("name")));}else{Check(a.operation=="settings.system.autodetect"&&a.arguments.empty(),"exact Auto schema");++host.observations;if(!observe){e="observation failed";return false;}PerformancePresetSignals signals;signals.steamDeck=true;p=DetectPerformancePreset(signals).preset;}if(!p)return false;out=Patch(*p);return true;});}
 void Accept(const ControlAction& p){Check(runtime.CanDispatchControlAction(p,time),"proposal still eligible");ActionInvocation a;Check(runtime.ResolveAction(p.action,a,error,&*p.proposal),"actual typed argument resolved");auto prior=Widget().accepted;Check(Dispatch(a).code==SettingsCode::Ok,"transaction generated edit succeeds");Check(SettingsValueEqual(prior,Widget().accepted),"operation alone cannot change authoritative widget");Sync();Check(runtime.AcknowledgeControlProposal(p.node,p.proposalToken,true),"ACK after real transaction readback");Frame();Check(SettingsValueEqual(Widget().accepted,*p.proposal),"choice paints accepted typed readback");}
 Runtime::EventEffects Event(const char* name){Runtime::EventEffects e;Check(runtime.RunEvent(name,time,e,error),error.c_str());return e;}
};
static void Semantics(const std::string& source,const std::string& locale){View v(source,locale);auto baseline=v.host.live;Check(v.Alias("draftPreset")=="balanced"&&v.Alias("baselinePreset")=="balanced","exact initial aliases");Check(v.runtime.FocusControl("settings_preset",v.time),"focus first authored performance control");v.Key(MenuInput::Next);Check(v.runtime.FocusedControl()=="settings_autodetect","preset then Auto keyboard order");v.Key(MenuInput::Next);Check(v.runtime.FocusedControl()=="settings_brightness","existing slider order follows performance band");v.Open();v.Key(MenuInput::End);v.Frame();Check(v.Widget().highlight=="settings_preset-option-5"&&v.Widget().firstVisible>0,"sixth choice reached beyond five visible rows");v.Key(MenuInput::Back);v.Frame();Check(!v.Widget().popupOpen&&v.runtime.TakeActions().empty()&&SettingsValuesEqual(v.tx.Draft(),baseline),"Back cancels highlight without writing");
 std::set<std::string> footprint(PerformancePresetTargets().begin(),PerformancePresetTargets().end());unsigned i=0;for(auto& p:PerformancePresets()){auto proposal=v.Select(i++);Check(std::get<std::string>(*proposal.proposal)==p.name,"all six exact canonical names");auto before=v.tx.Draft();v.Accept(proposal);for(auto& [k,x]:v.Patch(p))Check(SettingsValueEqual(v.tx.Draft().at(k),x),"generated target accepted");for(auto& [k,x]:before)if(!footprint.contains(k))Check(SettingsValueEqual(v.tx.Draft().at(k),x),"all21 unrelated custom values preserved");Check(v.Alias("draftPreset")==p.name&&v.Alias("baselinePreset")=="balanced","draft alias changes, baseline stays exact");}
 Check(v.host.writes==0&&SettingsValuesEqual(v.host.live,baseline),"six selections zero live writes");auto refused=v.Select(0);Check(v.runtime.AcknowledgeControlProposal(refused.node,refused.proposalToken,false),"refusal ACK");v.Frame();Check(std::get<std::string>(v.Widget().accepted)=="ultra","refused proposal preserves old readback");auto effects=v.Event("autoDetect");Check(effects.stateChanges.empty()&&effects.actions.size()==1,"Auto event one action zero writes");auto before=v.tx.Draft();Check(v.Dispatch(effects.actions[0],false).code==SettingsCode::Invalid&&SettingsValuesEqual(v.tx.Draft(),before),"failed observation preserves whole draft");v.message="#str_229985";v.Sync();v.Frame();auto message=v.runtime.PresentedValue("settings-message","text");Check(message&&message->text=="#str_229985","failed observation uses existing localized status");Check(v.Dispatch(effects.actions[0]).code==SettingsCode::Ok,"shared detected expansion succeeds");v.Sync();v.Frame();PerformancePresetSignals signals;signals.steamDeck=true;Check(v.Alias("draftPreset")==DetectPerformancePreset(signals).preset->name&&v.host.writes==0,"detected readback with zero writes");Check(v.Event("apply").actions.empty(),"unsupported Apply still blocked");
 Check(v.runtime.FocusControl("settings_brightness_number",v.time)&&v.runtime.BeginNumberEdit("settings_brightness_number",v.error,v.time),"begin real paired Number");auto n=v.runtime.GetWidgetState("settings_brightness_number")->number;Check(v.runtime.SetNumberSelection("settings_brightness_number",n->identity,0,n->state.text.size(),v.error,v.time),"select Number");n=v.runtime.GetWidgetState("settings_brightness_number")->number;Check(v.runtime.ReplaceNumberSelection("settings_brightness_number",n->identity,"-",v.error,v.time),"unconfirmed invalid local text");NumberDraftSummary d;Check(v.runtime.QueryNumberDrafts(d,v.error,v.time)&&d.blocking.size()==1,"actual local barrier blocks");v.pending=true;v.Sync();v.Frame();Check(!v.runtime.CanActivateControl("settings_preset",v.time)&&!v.runtime.CanActivateControl("settings_autodetect",v.time),"both new controls blocked");Check(v.Event("autoDetect").actions.empty()&&v.Event("apply").actions.empty(),"named events cannot bypass local drafts");Check(v.Dispatch(effects.actions[0]).code==SettingsCode::Busy,"new local buffer invalidates queued operation");Check(v.runtime.DiscardNumberDrafts(d.barrier,v.error,v.time),"explicit exact local discard");v.pending=false;v.Sync();v.Frame();Check(v.runtime.CanActivateControl("settings_preset",v.time)&&v.runtime.CanActivateControl("settings_autodetect",v.time),"discard enables operations again");std::string snapshot;auto draft=v.Alias("draftPreset");Check(v.runtime.SaveSnapshot(snapshot,v.error,v.time),"source-bound save");v.runtime.CloseDocument();std::vector<Diagnostic> ds;Check(v.runtime.LoadDocument(source,"guis/menu/settings/system.q4ui",ds)&&v.runtime.RestoreSnapshot(snapshot,v.error,v.time),"resource-style exact source recreation");v.Sync();v.Frame();Check(v.Alias("draftPreset")==draft&&v.Alias("baselinePreset")=="balanced"&&v.runtime.TakeActions().empty(),"aliases survive without action replay");}
static void TextFits(View& v,const char* id){auto* e=v.Element(id);auto size=e->GetBox().GetSize(Rml::BoxArea::Content);bool found=false;for(int i=0;i<e->GetNumChildren();++i)if(auto* t=dynamic_cast<Rml::ElementText*>(e->GetChild(i)))for(auto& line:t->GetLines()){found=true;if(line.position.x+line.width>size.x+1.1f||line.position.y+t->GetLineHeight()>size.y+1.1f)std::fprintf(stderr,"fit %s text=%s box=%g,%g line=%g,%g,%d lineheight=%g\n",id,line.text.c_str(),size.x,size.y,line.position.x,line.position.y,line.width,t->GetLineHeight());Check(line.position.x+line.width<=size.x+1.1f,"localized line fits content width");Check(line.position.y+t->GetLineHeight()<=size.y+1.1f,"localized line fits flowing height");}Check(found,"essential text generated actual lines");}
static void Opening(View& v,float density,int width,int height,bool wholeFirstSetting){
 v.viewport.width=width;v.viewport.height=height;v.viewport.displayScale=density;
 Check(v.tx.Edit(View::Owner,{{"com_performancePreset",std::string("balanced")}}).code==SettingsCode::Ok,"opening default draft");v.Sync();v.Frame();
 v.Element("settings-body")->SetScrollTop(0);v.Frame();
 auto body=v.Box("settings-body"),first=v.Box("settings_brightness_row"),footer=v.Box("settings-footer");
 Check(body.height>=92*density,"opening retains room for a complete numeric control");
 Check(footer.y>=body.y+body.height&&footer.y+footer.height<=height+.5f,"footer remains visible below scrolling settings");
 for(auto* id:{"settings_back","settings_apply"}){auto b=v.Box(id);Check(b.height>=44*density-.5f&&b.x>=0&&b.x+b.width<=width+.5f,"footer preserves full size targets inside viewport");}
 for(auto* id:{"settings-title","settings-message","settings_back-label","settings_apply-label"})TextFits(v,id);
 if(wholeFirstSetting){
  if(first.y+first.height>body.y+body.height+.5f){std::fprintf(stderr,"opening first=%g,%g body=%g,%g density=%g\n",first.y,first.height,body.y,body.height,density);for(auto* id:{"settings-footer","settings-message","settings-actions","settings_back","settings_apply"}){auto b=v.Box(id);std::fprintf(stderr,"%s %g,%g %gx%g\n",id,b.x,b.y,b.width,b.height);}}
  Check(first.y>=body.y&&first.y+first.height<=body.y+body.height+.5f,"opening shows complete first setting after preset band");
 }
}
static void Layout(View& v,float density,int width,int height){std::fprintf(stderr,"layout %dx%d density=%g expansion=%g\n",width,height,density,v.host.expansion);v.viewport.width=width;v.viewport.height=height;v.viewport.displayScale=density;std::istringstream labels(v.host.strings.at("#str_229977"));std::string label;size_t longest=0;unsigned candidate=0,index=0;while(std::getline(labels,label,';')){if(label.size()>longest){longest=label.size();candidate=index;}++index;}Check(v.tx.Edit(View::Owner,{{"com_performancePreset",std::string(PerformancePresets()[candidate].name)}}).code==SettingsCode::Ok,"select longest localized readback for fit");v.Sync();Check(v.runtime.FocusControl("settings_preset",v.time),"preset reachable");v.Frame();auto box=v.Box("settings_preset");Check(box.x>=0&&box.x+box.width<=width+1,"selector within horizontal viewport");TextFits(v,"settings_preset-label");TextFits(v,"settings_preset-value");v.Open();v.Key(MenuInput::End);v.Frame();auto popup=v.Box("settings_preset-popup");Check(popup.x>=-.1f&&popup.y>=-.1f&&popup.x+popup.width<=width+.2f&&popup.y+popup.height<=height+.2f,"popup fully clamped to viewport");for(unsigned option=0;option<6;++option)TextFits(v,("settings_preset-option-"+std::to_string(option)+"-label").c_str());v.Key(MenuInput::Back);v.Frame();Check(v.runtime.FocusControl("settings_autodetect",v.time),"Auto remains reachable at narrow viewport");v.Frame();auto button=v.Box("settings_autodetect"),body=v.Box("settings-body");Check(button.x>=0&&button.x+button.width<=width+1,"Auto horizontally contained");if(button.y<body.y-.5f||button.y+button.height>body.y+body.height+.5f)std::fprintf(stderr,"auto density=%g expansion=%g button=%g,%g,%g,%g body=%g,%g,%g,%g\n",density,v.host.expansion,button.x,button.y,button.width,button.height,body.x,body.y,body.width,body.height);Check(button.y>=body.y-.5f&&button.y+button.height<=body.y+body.height+.5f,"focused Auto wholly revealed in scroll body");TextFits(v,"settings_autodetect-label");v.Key(MenuInput::Accept);auto actions=v.runtime.TakeActions();Check(actions.size()==1&&actions[0].event=="autodetect","Auto button queues guarded authored event");v.Frame();auto old=v.Box("settings_preset");v.Frame();box=v.Box("settings_preset");Check(old.x==box.x&&old.y==box.y&&old.width==box.width&&old.height==box.height,"unchanged layout settles");Check(v.host.draws>0&&v.host.writes==0,"actual render and zero native writes");}
int main(int argc,char** argv){
 Check(argc==3,"page and locale directory args");auto source=Read(argv[1]);std::string dir=argv[2];Semantics(source,dir+"/english_openq4.lang");
 for(auto* locale:{"english","spanish","polish","russian","french","italian"})for(float expansion:{1.f,1.4f}){
  std::fprintf(stderr,"locale %s expansion=%g\n",locale,expansion);
  View view(source,dir+"/"+locale+"_openq4.lang",1,1280,720,expansion);
  // Reuse the loaded instance across the viewport matrix: this also proves
  // reflow after actual resize/density changes, with stable accepted aliases.
  for(auto dims:{std::array<int,3>{1280,720,100},std::array<int,3>{1280,720,125},std::array<int,3>{1280,720,200},std::array<int,3>{800,600,100}})
   {Opening(view,dims[2]/100.f,dims[0],dims[1],std::string(locale)=="english"&&expansion==1.f);Layout(view,dims[2]/100.f,dims[0],dims[1]);}
 }
 std::printf("PASS %u checks; actual SYSTEM/RmlUi, six locales +40%% width stress, counted transaction host.\n",checks);
}
